import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import service from "../service-account.enc";
import useSWR from "swr";
import axios from "axios";

const fetchWithData = (url, encrypt) =>
  axios.post(url, { data: encrypt }).then((res) => res.data);

export default function Home() {
  const { data, error } = useSWR(
    ["/api/decrypt", service.encrypted],
    fetchWithData
  );
  if (error) return <div>failed to load</div>;
  if (!data) return <div>Loading...</div>;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>ENV Data: {JSON.stringify(data, null, 2)}</h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
